spring.application.name=RubiumLead
server.port=8080

notion.token=${notion.token:}
notion.data-source-id=${notion.data-source-id:}

tavily.api-key=${tavily.api-key}




#  ${NOTION_TOKEN:}
#notion.data-source-id=$git status
#git add .
#git commit -m "Add chatbot"
#git push origin main{NOTION_DATA_SOURCE_ID:}